import { Cairo } from 'next/font/google';
import "./globals.css";
import Navbar from "./components/home/Navbar";
import Footer from './components/home/Footer';

const cairo = Cairo({
  subsets: ['arabic', 'latin'],
  weight: ['400', '700', '900'], // حسب الحاجة
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <head>
        {/* أي محتوى إضافي */}
      </head>
      <body className={cairo.className}>
      <Navbar/>
        {children}
            <Footer/>

      </body>
    </html>
  );
}
